version: "3.8"
services:
  workspace:
    image: "mcr.microsoft.com/vscode/devcontainers/base:bullseye"
    command: sleep infinity
    volumes:
      - root-node-volume:/workspace/node_modules
      - frontend-node-volume:/workspace/frontend/node_modules
      - backend-venv-volume:/workspace/backend/.venv
      - ../:/workspace
volumes:
  root-node-volume:
  frontend-node-volume:
  backend-venv-volume:
