name: Publish API documentation

on:
  push: # TODO: 最終的には main ブランチへのプッシュ時に限定する。併せて、Settings > Environments > Deployment branches and tags にて、main ブランチからのみデプロイできるようにする。

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.12.2-slim-bullseye

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Set environment variable
        run: |
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - name: Generate OpenAPI spec
        run: |
          poetry run python -c "from src.main import print_openapi_spec; print_openapi_spec()" > openapi-spec.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Convert JSON to HTML
        run: |
          mkdir docs
          npx @redocly/cli@1.9.1 build-docs openapi-spec.json --output docs/api-doc.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: backend/docs

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
